/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SUS
 */
public class perpustakaan extends javax.swing.JFrame {

    /**
     * Creates new form perpustakaan
     */
    public perpustakaan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        buku1 = new javax.swing.JLabel();
        buku2 = new javax.swing.JLabel();
        buku3 = new javax.swing.JLabel();
        bbuku1 = new javax.swing.JButton();
        bbuku2 = new javax.swing.JButton();
        bbuku3 = new javax.swing.JButton();
        judulbuku = new javax.swing.JLabel();
        penulis = new javax.swing.JLabel();
        penerbit = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        deskripsi = new javax.swing.JLabel();
        isijudul = new javax.swing.JTextField();
        isipenulis = new javax.swing.JTextField();
        isipenerbit = new javax.swing.JTextField();
        isitanggal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        isideskripsi = new javax.swing.JTextArea();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        judul.setFont(new java.awt.Font("Baskerville Old Face", 1, 30)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("PERPUSTAKAAN ");

        judul2.setFont(new java.awt.Font("Baskerville Old Face", 1, 30)); // NOI18N
        judul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul2.setText("UNIVERSITAS TRUNOJOYO MADURA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(judul2)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        buku1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/716010920_si_juki_-_lika-liku_anak_kos.jpg"))); // NOI18N

        buku2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9786022202431_9786022202431.jpg"))); // NOI18N

        buku3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9786020459691_Si-Juki-Vs-Dompet-Kosong.jpg"))); // NOI18N

        bbuku1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        bbuku1.setText("DETAIL");
        bbuku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuku1ActionPerformed(evt);
            }
        });

        bbuku2.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        bbuku2.setText("DETAIL");
        bbuku2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuku2ActionPerformed(evt);
            }
        });

        bbuku3.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        bbuku3.setText("DETAIL");
        bbuku3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuku3ActionPerformed(evt);
            }
        });

        judulbuku.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        judulbuku.setText("JUDUL BUKU              :");

        penulis.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        penulis.setText("PENULIS                      :");

        penerbit.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        penerbit.setText("PENERBIT                    :");

        tanggal.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        tanggal.setText("TANGGAL TERBIT      :");

        deskripsi.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        deskripsi.setText("DESKRIPSI                    :");

        isideskripsi.setColumns(20);
        isideskripsi.setRows(5);
        jScrollPane1.setViewportView(isideskripsi);

        hapus.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        keluar.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(bbuku1)
                        .addGap(104, 104, 104)
                        .addComponent(bbuku2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bbuku3)
                        .addGap(73, 73, 73))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hapus)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(deskripsi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(judulbuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(penulis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(penerbit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buku1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(buku2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(buku3)))
                                        .addGap(65, 65, 65))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(isitanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(isipenerbit)
                                            .addComponent(isipenulis)
                                            .addComponent(isijudul))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(keluar)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buku1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buku2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buku3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbuku1)
                    .addComponent(bbuku2)
                    .addComponent(bbuku3))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judulbuku)
                    .addComponent(isijudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(penulis)
                    .addComponent(isipenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(penerbit)
                    .addComponent(isipenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggal)
                    .addComponent(isitanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deskripsi)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus)
                    .addComponent(keluar))
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbuku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuku1ActionPerformed
        isijudul.setText("Si Juki Lika-Liku Anak Kos");
        isipenulis.setText("Faza Meonk");
        isipenerbit.setText("Elex Media Komputindo");
        isitanggal.setText("7 Juni 2016");
        isideskripsi.setText("Mengisahkan keseharian Juki yang nama \naslinya adalah Muhammad Marzuki sebagai \nrepresentasi mahasiswa yang hidup sebagai \nanak kos yang kreatif dan kocak. Dibarengi juga \ndengan berbagai macam kesulitan yang biasa \ndialami oleh anak kos seperti kehabisan uang \nbulanan, tugas yang menumpuk dan ibu kos \nyang menagih uang sewa.");        
    }//GEN-LAST:event_bbuku1ActionPerformed

    private void bbuku2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuku2ActionPerformed
        isijudul.setText("Si Juki Cari Kerja");
        isipenulis.setText("Faza Meonk");
        isipenerbit.setText("Elex Media Komputindo");
        isitanggal.setText("18 Oktober 2017");
        isideskripsi.setText("Setelah lulus SMA, Juki bocah nyentrik yang\nngakunya Anti mainstream memutuskan\nuntuk langsung bekerja. Dengan keterampilan\nseadanya, kelakuan nyeleneh, dan teman-\nteman yang ajaib, Juki memulai\npetualangannya.");  
    }//GEN-LAST:event_bbuku2ActionPerformed

    private void bbuku3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuku3ActionPerformed
        isijudul.setText("Si Juki Vs Dompet Kosong");
        isipenulis.setText("Faza Meonk");
        isipenerbit.setText("Elex Media Komputindo");
        isitanggal.setText("01 Juli 2020");
        isideskripsi.setText("Cerita Si Juki memang ga pernah jauh2 dari\nisi kantong alias dompet. Kali ini pun, cerita Si\nJuki berkisar tentang bagaimana cara\nmenabung yang baik.");
    }//GEN-LAST:event_bbuku3ActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        isijudul.setText("");
        isipenulis.setText("");
        isipenerbit.setText("");
        isitanggal.setText(""); 
        isideskripsi.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbuku1;
    private javax.swing.JButton bbuku2;
    private javax.swing.JButton bbuku3;
    private javax.swing.JLabel buku1;
    private javax.swing.JLabel buku2;
    private javax.swing.JLabel buku3;
    private javax.swing.JLabel deskripsi;
    private javax.swing.JButton hapus;
    private javax.swing.JTextArea isideskripsi;
    private javax.swing.JTextField isijudul;
    private javax.swing.JTextField isipenerbit;
    private javax.swing.JTextField isipenulis;
    private javax.swing.JTextField isitanggal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judulbuku;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel penerbit;
    private javax.swing.JLabel penulis;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables
}
